joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Position Controllers --------------------------------
frontLeftWheel_joint_position_controller:
 type: effort_controllers/JointPositionController
 joint: frontLeftWheel_joint
 pid: {p: 20.0, i: 0.0, d: 0.1}

frontRightWheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: frontRightWheel_joint
  pid: {p: 20.0, i: 0.0, d: 0.1}

rearLeftWheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rearLeftWheel_joint
  pid: {p: 20.0, i: 0.0, d: 0.1}

rearRightWheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rearRightWheel_joint
  pid: {p: 20.0, i: 0.0, d: 0.1}

shoulder_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_joint
  pid: {p: 250.0, i: 0.1, d: 10.0}

slider_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: slider_joint
  pid: {p: 100.0, i: 0.00, d: 10.0}
# pid 100,0,10
R1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: R1_joint
  pid: {p: 2000.0, i: 0.0, d: 50.0}

R2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: R2_joint
  pid: {p: 1500.0, i: 0.0, d: 50.0}

R3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: R3_joint
  pid: {p: 2000.0, i: 0.0, d: 50.0}

left_act_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_act_joint
  pid: {p: 20.0, i: 0.0, d: 0.1}

camera_head_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: camera_head_joint
  pid: {p: 20.0, i: 0.0, d: 0.1}

mop_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: mop_joint
  pid: {p: 20.0, i: 0.0, d: 0.1}
